pypa/bandersnatch

src/bandersnatch/default.conf, src/bandersnatch/main.py, src/bandersnatch/mirror.py, src/bandersnatch/package.py, src/bandersnatch/tests/test_main.py, src/bandersnatch/tests/test_mirror.py, src/bandersnatch/tests/test_package.py
We've decided to move all deletion logic to a batch job so that we can
leave bandersnatch stateless. So this diff removes all the deletion logic
that is only working today for simple, serversig and json files.
This will all be moved and well unit tested in a new 'verify' option
that bandersnatch will get. This will have an optional `--delete`
that will clean up unowned files and packages (simple + JSON files) with 0 remaining release files.
=> Remove broken delete logic

docs/filtering_configuration.md
The filename filtering functionality is not implemented.  Remove it from the documentation.
=> Fix another documentation issue

doc_requirements.txt, docs/CONTRIBUTING.md, docs/installation.md, tox.ini
This changes the install docs on read_the_docs to require python 3.6.
It also adds a reference to github flow to the contributing document. 
Change the reference to bitbucket in the documentation to point to github.
Adds zest.releaser to the doc_requirements.txt because it's referenced in the autodocs.
=> Python36 doc changes

.travis.yml, doc_requirements.txt, docs/conf.py, src/bandersnatch/main.py, src/bandersnatch/mirror.py, src/bandersnatch/tests/test__bandersnatch_plugins__blacklist_name.py, src/bandersnatch_filter_plugins/blacklist_name.py, tox.ini
This is to address issue #28 
The problem is the configuration object being used by the plugins does not load the configuration file passed as a command line argument in main() as a result the plugins are ignoring setting values from the actual configuration file.
This fixes the issue by populating the configuration singleton with the configuration file name.
This also includes some code that evidently didn't get included in the release plugin that was needed to actually validate the release versions.
=> Filter plugin fixes

src/bandersnatch/mirror.py
>> Issue: [B101:assert_used] Use of assert detected. The enclosed code will be removed when compiling to optimised byte code.
Severity: Low   Confidence: High
Location: src/bandersnatch/mirror.py:350
This change changes from using an assert that will be removed by byte compiling with a check that raises
a RuntimeError exception instead.
=> Fix a security issue found by bandit:

.gitignore, .pre-commit-config.yaml, .travis.yml, docs/conf.py, mypy.ini, setup.py, src/bandersnatch/__init__.py, src/bandersnatch/buildout.py, src/bandersnatch/configuration.py, src/bandersnatch/filter.py, src/bandersnatch/log.py, src/bandersnatch/main.py, src/bandersnatch/master.py, src/bandersnatch/mirror.py, src/bandersnatch/package.py, src/bandersnatch/release.py, src/bandersnatch/tests/conftest.py, src/bandersnatch/tests/test_filter.py, src/bandersnatch/tests/test_main.py, src/bandersnatch/tests/test_master.py, src/bandersnatch/tests/test_mirror.py, src/bandersnatch/tests/test_package.py, src/bandersnatch/tests/test_utils.py, src/bandersnatch/utils.py, src/bandersnatch/verify.py, src/bandersnatch_filter_plugins/blacklist_name.py, src/bandersnatch_filter_plugins/whitelist_name.py, test-requirements.txt, tox.ini
to be honest, I'm not exactly sure how I got here -- I was reading through the project to try and understand what it does and noticed #15 and somehow my first thought was "oh hey, that sounds like fun".  I applied it to a few modules and then got to a point where I needed to actually understand the code to make further progress and so I decided to commit what I had and make a PR.
This also (selfishly?) adds [pre-commit](https://pre-commit.com) as an easier way to run linting (~I noticed there wasn't currently any automated linting in CI so I added it!~ EDIT: had to change from pep8 -> flake8 so that type annotations weren't false positives) -- this part isn't entirely necessary as mypy can be invoked directly.
=> Introduce mypy and enforce it on a few files

requirements.txt, setup.py
pkg_resources is needed and needs to be explicitly defiend for non virtual environments where setuptools is always implicitly there.
- Found this building bandersnatch 3.0 for testing inside of Facebook, where we don't use Virtual Environments.
=> Add setuptools as a requirement

src/bandersnatch/package.py, src/bandersnatch/verify.py
https://github.com/asottile/yesqa
I had to [manually edit one comment][0].
- this line previously excluded any lint on that line
- `noqa` comments for a specific code [need a `:`][1] (yeah, their comment is
wrong)
- yesqa knows this so it converted `# noqa F821` -> `# F821`
[0]: https://github.com/pypa/bandersnatch/blob/ccc9a38/src/bandersnatch/package.py#L89
[1]: https://github.com/PyCQA/flake8/blob/3.5.0/src/flake8/defaults.py#L49
=> Run yesqa against all the files

src/bandersnatch/main.py, src/bandersnatch/verify.py
- I want to include this in my larger asyncio daemon @ Facebook
- Make the entry point async and start loop in main.py
- Move everything to fstrings
- Fix some small bugs:
-- always use our created executor
-- wrap all IO in executors
-- print unowned files only if there are unowned files in dry run mode
Test:
python3.6 -m venv /tmp/v
/tmp/v/bin/pip install --upgrade pip
/tmp/v/bin/pip install -e .
/tmp/v/bin/bandersnatch --debug verify --dry-run
/tmp/v/bin/bandersnatch --debug verify --json-update - Output: https://pastebin.com/G89VBGd6
=> Make verify.py more async program friendly

src/bandersnatch/package.py
Without this patch, bandersnatch skips a package as soon as it fails to download a single file.
In an environment with connectivity issues, e.g. where long downloads are difficult to complete, this means that large packages will never complete in practice, causing the mirror to fall behind.
This issue mostly manifests itself with several "deep learning" packages that appear to use PyPI for their continuous integration hosting.  mxnet* is a particular offender here, with multiple 300MB+ packages added per day.  At least tensorflow has a separate "nightlies" package which could separately be blacklisted if desired.
This patch lets bandersnatch at least try to download each file in the package before giving up, making substantially more progress during each run.  In practice, this has …
=> Try to download each remaining file in a package before bailing

src/bandersnatch/master.py
Temporary fix for #56. We issue a PURGE to the url if we get a stale serial. Not ideal, but a workaround until PyPI's caches are fixed to always return the up-to-date header.
=> Issue a purge request when we get a stale serial.

src/bandersnatch/main.py, src/bandersnatch/tests/test_main.py
I noticed this while working on a different issue, feels like we should not continue if the digest is unsupported rather than simply logging the error? I think the formatting of the error was also missing an argument.
=> Raise on unsupported digest

DEVELOPMENT.md, README.md, docs/CONTRIBUTING.md, setup.py
- Save future devs time by not trying to use 3.6.0
- We need `from typing import NamedTuple`
=> Document + enforce we need >= 3.6.1

src/bandersnatch/mirror.py
Fixes #27
The output varies when force cancelling the threads in this way. Usually it's fairly clean and immediate but I've seen instances where there's leftover output from the threads and once I got the following:
```
exception calling callback for <Future at 0x10fc176d8 state=finished returned NoneType>
Traceback (most recent call last):
File "/Users/yeray.diaz/.pyenv/versions/3.6.5/lib/python3.6/concurrent/futures/_base.py", line 324, in _invoke_callbacks
callback(self)
File "/Users/yeray.diaz/.pyenv/versions/3.6.5/lib/python3.6/asyncio/futures.py", line 414, in _call_set_state
dest_loop.call_soon_threadsafe(_set_state, destination, source)
File "/Users/yeray.diaz/.pyenv/versions/3.6.5/lib/python3.6/asyncio/base_events.py", line 621, in call_soon_threadsafe
self._check_closed()
File …
```
=> Force cancel on KeyboardInterrupt

setup.py, src/bandersnatch/__init__.py
- Lets allow people to install latest deps
- Leave requirements.txt that hard pin known working versions
Test install in a venv: https://pastebin.com/FUzsgcX6
Addresses #81
=> Revert setup.py to specify unversioned deps

src/bandersnatch/configuration.py, src/bandersnatch/tests/test_configuration.py, src/bandersnatch/tests/test_mirror.py
I fixed this [issue](https://github.com/pypa/bandersnatch/issues/95). #95 
I think the problem was configuration module tries to read default and system configuration. The problem is when you comment any section in system configuration, it'll read that section through default configuration.
=> bug fix: reading either default or system configuration instead of both

src/bandersnatch/main.py
Hi
Sometimes I just want to see `bandersnatch` options but it tries to mirror everything so I changed the code for that part and I added `--version` option to make sure I'm using the latest version due to `force-check` option.
thanks
=> prevent executing bandersnatch when no argument has entered

Dockerfile, src/runner.py
- Use latest Python 3
- Install all tested Python module version in requirements.txt
Tested build via `docker build --network=host --tag bandersnatch .`:
https://pastebin.com/0ZGgMUtA
Addresses #88 - Will see what the best way to automate building this image on every commit or release? Don't know what's the hotness with Docker (lost inside Facebook)
=> Add a reference Docker File

MANIFEST.in, setup.py, src/bandersnatch/filter.py, src/bandersnatch/mirror.py, src/bandersnatch/package.py, src/bandersnatch/tests/ci.conf, src/bandersnatch/tests/plugins/test_blacklist_name.py, src/bandersnatch/tests/plugins/test_whitelist_name.py, src/bandersnatch/tests/test_configuration.py, src/bandersnatch/tests/test_filter.py, src/bandersnatch/tests/test_main.py, src/bandersnatch/tests/test_mirror.py, src/bandersnatch/unittest.conf, test_runner.py
- Turning on all plugins by default is misleading and causes unexpected issues
- `black` project has all it's versions as beta, so we were filtering them by default and it clobbered my 3 production mirrors Simple API for `black`
- We now have all plugins off unless explicitly configuring all or the plugins name
Fixes #140
Testing:
- Fix all unit tests
- Edit Integration test to include black
- Manually run Integration with all plugins enabled - See CI fail
- Manually run with ONLY whitelist_project enabled and see it work as expected
=> Fix turning on all plugins by default

src/bandersnatch/package.py
- Decided to leave @ info level but only print once.
Fixes #146
=> Make package filtering logging less noisey when disabled

src/bandersnatch/filter.py, src/bandersnatch/mirror.py, src/bandersnatch_filter_plugins/blacklist_name.py, src/bandersnatch_filter_plugins/filename_name.py, src/bandersnatch_filter_plugins/latest_name.py, src/bandersnatch_filter_plugins/prerelease_name.py, src/bandersnatch_filter_plugins/regex_name.py, src/bandersnatch_filter_plugins/whitelist_name.py
- Only initialize if the plugin is enabled in config
- Move all plugins to store their loaded state as a static / class variable
Fixes #195 #193 #147
=> Make plugins less noisey and more stateful

MAINTAINERS.md, README.md
- Advertise at the top of the README.md that we're looking for new maintainers
- Add detail about what being a maintainer is
This is action post the Maintainer's summit. We discussed that this would be a good move to try and help attract new maintainers and explain what it is to be one.
cc: @brainwane @jreese - Need to get this in front of other people @ the Summit somehow.
Fixes #213
=> Add a Maintainers guide + Mission Statement to README.md

requirements.txt
- Stop getting PRs for now from PyUP.
=> Add version specifier for urllib3 until requests get to support 1.25

setup.cfg, setup.py, src/bandersnatch/filter.py, src/bandersnatch/main.py, tox.ini
This is to address an issue where the plugin class filter method had different arguments in different versions of bandersnatch.   This creates an issue where bandersnatch could load plugins from a different package and which had a plugin class with a filter method with arguments different than what bandersnatch was passing.  Which would generate an exception.
This change adds a version value to the pkg_resource group for the plugins.
This allows the value to be changed when a breaking change is made to the plugin base classes.  In order to insure the plugin classes match the expected classes used by the code calling the plugins.
This change sets the version of the plugin interface on master to v2 and updates the values in the setup.cfg file to match.  As a result, bandersnatch now loads …
=> Version plugin api

README.md
`pypi.org/stats` is gone and therefore `pypistats` doesn't work any more (as per https://github.com/cooperlees/pypistats/pull/6 ). Instead link to the guidance page about analyzing PyPI downloads.
=> Remove unmaintained links

docs/filtering_configuration.md
The sample configuration snippet related to platform filtering was missing the blacklist section.
=> Fix example of platform filtering in docs

src/bandersnatch_filter_plugins/prerelease_name.py
Extend PRERELEASE_PATTERNS to match multiple digits after the prerelease tag.
- Some packages have versions beyond 9 e.g. https://pypi.org/project/scikit-vis/0.0.2.dev12/  
- Some packages use a date scheme as the suffix e.g. https://pypi.org/project/lalsuite/6.57.1.dev20190613/
=> Match prerelease versions with multiple digit suffixes

.pyup.yml
- Remove the following
```
cooper-mbp1:bandersnatch cooper$ /tmp/bb/bin/yamllint .pyup.yml
.pyup.yml
1:1       warning  missing document start "---"  (document-start)
6:10      warning  truthy value should be one of [false, true]  (truthy)
9:10      warning  truthy value should be one of [false, true]  (truthy)
12:10     warning  truthy value should be one of [false, true]  (truthy)
14:13     warning  truthy value should be one of [false, true]  (truthy)
```
- Remove assignees
More attempts to find a fix for https://github.com/pyupio/pyup/issues/350
=> pyup.yml - Apply all yamllint suggestions

requirements_docs.txt
- 0.15.1 Py3 version/wheel + sdist seem gone ...
Addresses #293
=> Move to `docutils==0.15.1.post1`

docs/mirror_configuration.md, src/bandersnatch/default.conf, src/bandersnatch/main.py, src/bandersnatch/mirror.py, src/bandersnatch/package.py, src/bandersnatch/tests/test_main.py, src/bandersnatch/unittest.conf
This PR adds a differential file list capability to bandersnatch.
The capability is useful in cases where a user wants to synchronize pypi to an offline server without having to determine the diffs each time a mirror command is executed.  The diff file can be used to only send diff to a synchronization disk, or to send new files through a diode to an offline or upstream pypi mirror.
=> Add a differential file list capability

.travis.yml
- Lets see if `trunk` segmentation faults as well like 3.8 is at the moment
=> Add Nightly Python build to CI

src/bandersnatch/main.py, src/bandersnatch/mirror.py
- Planning to add another sub command and main.py is to long
- Lets move the mirror logic to mirror.py
- Lets also ensure we always return an int and error when we should ...
Make Unit tests and CI pass to ensure we're good.
=> [refactor] Move mirror logic out of main.py into mirror.py

setup.cfg, src/bandersnatch/__init__.py, src/bandersnatch/delete.py, src/bandersnatch/main.py, src/bandersnatch/tests/test_delete.py, src/bandersnatch/tests/test_verify.py, src/bandersnatch/verify.py, test_runner.py
- Look at PyPI JSON and delete all the local files if they exist
- Support dryrun
Add unittests in `test_delete.py` and add the deletion of `black` to CI run.
Helps with #307 by giving people a way to clean out downloaded packages.
=> [delete] Add new subcommand to delete package artifacts

src/bandersnatch/configuration.py
- We were always printing the deprecation - Bit silly
- Now if we find the old setting set, only then will we error / warn
=> Only Print conf deprecations if found

.travis.yml
- Lets expect Python 3.8 to pass ...
- Also move nightly tox env to expect Python3.9
=> Move TravisCI to test on real Python3.8

requirements_test.txt, src/bandersnatch/main.py
Fix #325 : Replaced subparser function parameter from Any to argparse._SubParsersAction
=> Added subparsers action type

.github/workflows/ci.yml, .travis.yml, docs/bandersnatch.rst
- Have TravisCI run doc tests to ensure we don't break
- Have doc_build and lint in 3.7 to give tools more time to be 3.8 ready (should still lint and build docs the same)
- Add 3.8 to GitHub Actions
- Remove lint from GitHub and only run on TravisCI (no need to run on every platform)
=> Restore missing docs CI + Tune CI

src/runner.py
Hello there,
Maybe this could solve some of the problems (#393 ):
* Change type of interval argument to int
* Remove hardcoded the bandersnatch path; instead run it by using the `bandersnatch.main` module
I couldn't solve the configuration part, but I think that could be achievable through Dockerfile, maybe?.
=> bugfix in runner.py:

requirements.txt, requirements_test.txt, setup.cfg, src/bandersnatch/master.py, src/bandersnatch/mirror.py, src/bandersnatch/tests/test_master.py, src/bandersnatch/tests/test_mirror.py, tox.ini
- Async def up Master PyPI XML RPC Calls
- Wrap calls in `asyncio.run_until_complete` in `mirror.py`
- Pull in asynctest + use CoroutingMock's until we're >= 3.8
See integration tests still pass
=> Replace xmlrpc2 with aiohttp-xmlrpc

src/bandersnatch/mirror.py
- Today we would go off and save that we had a successful sync
- This is not always true when people ctrl + c mid sync, so lets not save that we had a successful sunc to disk
Fixes #362
=> Flag errors when KeyboardInterrupt raised during sync

.github/workflows/ci.yml
- We should have all the deps installed before unittests to ensure we can import everything
This was found during the refactor from threads + requests to aiohttp (splitting the PRs so the cut over is as small as possible)
=> Install base requirements before unittests on GitHub Actions

docs/index.rst, src/bandersnatch/package.py, src/bandersnatch/tests/test_package.py
- PEP503 says we only need to store the normalized path / name for packages
- Moderns pip supports this
- Lets remove the legacy normalization and 1.5 non normalized directories for simple html
- Also make package.py full mypy / PEP484 compliant
Have made a note in documentation about this.
Tests:
- Update tests to only expect normalized directories
Fixes #138
=> Remove non all PEP503 conformant paths

src/bandersnatch/tests/test_package.py
- Remove use of os.stat() + recreate a new Path() object and use stat()
- That ensures we don't use stat from the same Path() object and no cache entry
Could not repro the failures locally :(
Fixes #453
=> Make test_package_sync_does_not_touch_existing_local_file use Path()

setup.cfg, src/bandersnatch/__init__.py, src/bandersnatch/default.conf, src/bandersnatch/mirror.py, src/bandersnatch/package.py, src/bandersnatch/tests/ci.conf, src/bandersnatch/tests/conftest.py, src/bandersnatch/tests/test_configuration.py, src/bandersnatch/tests/test_main.py, src/bandersnatch/tests/test_package.py, src/bandersnatch/unittest.conf, src/bandersnatch/verify.py
- No longer need to store the Simple API other than PEP normalized name
- Add a cleanup function to remove uneeded directories from existing mirrors
Tests:
- Add a unit test for cleanup
- Ensure current unittests pass
- See CI run pass
=> Make packages only store PEP 503 Simple API Directory

src/bandersnatch/package.py, src/bandersnatch/tests/ci.conf, src/bandersnatch/tests/conftest.py, src/bandersnatch/tests/test_package.py
- XMLRPC returns the raw_name
- Keeping raw_name to store this in the Simple HTML
Tests:
- Added new test `test_package_sync_handles_non_pep_503_in_packages_to_sync` that failed with using Foo as a package to sync
- This test does not use all normal PyTest fixtures on purpose
- Added more asserts around Mirror.errors
- Returned Foo from mocked out XMLRPC return
- Fixed a few tests with other little bugs uncovered by `assert not mirror.errors`
- Added `ACMPlus` to CI Integration run
Addresses part of #470
- Still need to workout if we want to normalize all the plugin names and compare the XMLRPC returned lists with their normalized named to avoid typos etc.
=> Fix deletion of finished Packages

src/bandersnatch/master.py, src/bandersnatch/verify.py
- Have session be a timeout object
- Pass in custom get timeout if provided
- Also fix verify's timeout until we merge it's master operations with master.py
Addresses #477
=> [master] Pass correct aiohttp timeout objects

requirements.txt, setup.cfg, src/bandersnatch/package.py, src/bandersnatch/tests/test_utils.py, src/bandersnatch/utils.py
- Add missing dependencies for importlib_resources from #479
- Rename utils.safe_name to bandersnatch_safe_name
- Also now pre-compile the safe_name regex
- Add unittest for bandersnatch_safe_name
=> Add unittest for new utils.safe_name

mypy.ini, src/bandersnatch/tests/test_filter.py, src/bandersnatch/tests/test_verify.py, src/bandersnatch/verify.py
Part of https://github.com/pypa/bandersnatch/issues/15
=> [verify]: Conform to PEP 484 type hints

src/bandersnatch/master.py, src/bandersnatch/tests/test_master.py
I am not sure about the unit test. I think we should only test correct argument is passed to aiohttp, whether aiohttp actually raise the exception should tested in aiohttp itself.
=> Raise error for bad response (#494)

src/bandersnatch/tests/plugins/test_filename.py, src/bandersnatch_filter_plugins/filename_name.py
I required more detailed platform selection to minimise the size of my mirrors. This will allow you to blacklist specific platforms within a platform set. For example you can exclude linux-armv7l but still mirror all other linux platforms.
=> Add more detailed platform choices

src/bandersnatch/master.py
- This then shares common settings - e.g. Proxy Environment trusting
- Connections are cleaned up @ the end in __aexit__ of Master
Tested by turning on Python warnings + Running Integration test on my laptop
Fixes #504
=> Change aiohttp-xmlrpc to use Master.session

.github/workflows/docker_upload.yml
Added the Github Action for automating pushing the `pypa/bandersnatch`
image to Docker Hub when a new release in published.
Closes https://github.com/pypa/bandersnatch/issues/88
=> Add GH Action for pushing to Docker Hub on Release

.travis.yml
- Travis is still on 3.8.0 while GitHub Actions is on 3.8.2
- Remove to stop uneeded duplication on old version of 3.8
- Add an integration run to nightly + allow to fail
- Don't hard code the dist to allow travis to change in the future as they upgrade
=> Remove Travis 3.8 tests

MANIFEST.in, setup.cfg
- Remove from MANIFEST.in and to package_data
- See if this helps the docker building
Testing:
1)
```
python3 -m venv /tmp/build_bs
/tmp/build_bs/bin/pip install --upgrade setuptools pip wheel
/tmp/build_bs/bin/python setup.py sdist
...
copying src/bandersnatch/default.conf -> bandersnatch-4.0.3/src/bandersnatch
copying src/bandersnatch/unittest.conf -> bandersnatch-4.0.3/src/bandersnatch
...
```
2)
```
tar xvzf bandersnatch-4.0.3.tar.gz
cooper-mbp1:dist cooper$ find bandersnatch-4.0.3 -name '*.conf'
bandersnatch-4.0.3/src/bandersnatch/unittest.conf
bandersnatch-4.0.3/src/bandersnatch/default.conf
```
Might help with #509
=> Move bandersnatch *.conf to setup.cfg

src/bandersnatch/master.py
- We were not setting sock* timeouts for aiohttp and only total
- Lets set total to 10 * config timeout setting
- e.g. default = 10 seconds, so we get a hard total timeout of a connection @ 100 seconds
Fixes #511
=> Move to seeting timeout only on session + 10 * Total timeout

.pre-commit-config.yaml, Dockerfile, requirements.txt, requirements_swift.txt, requirements_test.txt, setup.cfg, src/bandersnatch/storage.py, tox.ini
- Lets not cause default install to have all the swift deps
- Have tox install the extra swift deps
- Lets have docker include swift support so it can be enabled
- Lets disable the cache dir in docker build
- Also updated pre-commit
Fixes #534
=> Move swift deps to be a true extra install

src/bandersnatch/mirror.py, src/bandersnatch/package.py, src/bandersnatch/tests/ci-swift.conf, src/bandersnatch_storage_plugins/swift.py
- Uses the correct location reference to remove packages stored in swift
- Checks for `TypeError` during `_cleanup` calls to make sure to remove
invalid `todo` files that raise type errors
- Adds default swift container name to test swift CI config as an
example
- Fix swift `rmdir` implementation
- Don't include `.swiftkeep` files in `iterdir` output by default
- Add type hints to symlink methods
- Fix typo in `delete_file` exception handler in swift
- Add `is_symlink` check to `SwiftPath` and swift storage backend
- Add `absolute()` method to `SwiftPath`
- Fix and typehint swift lockfile
- Fixes #527
- Fixes #528
=> Swift bugfixes & type hints

src/bandersnatch/storage.py, src/bandersnatch/verify.py
- When downloading, verifying or deleting content, make sure we
use the `storage_backend` wrapped path plugin
- This is going to be really annoying and we probably should figure out
how to centralize these kinds of calls in a more natural way
- Fixes #539
Signed-off-by: Dan Ryan <dan.ryan@canonical.com>
=> Ensure use of `storage_backend` based path wrapper

docs/mirror_configuration.md, src/bandersnatch/default.conf, src/bandersnatch/master.py, src/bandersnatch/mirror.py, src/bandersnatch/tests/ci-swift.conf, src/bandersnatch/tests/ci.conf, src/bandersnatch/tests/plugins/test_storage_plugins.py, src/bandersnatch/tests/test_configuration.py, src/bandersnatch/unittest.conf
- Add `global-timeout` configuration parameter for configuring
`aiohttp`'s `total_timeout` setting
- Leave `timeout` as is for managing `sock_connect` and `sock_read`
- Update test configurations, ensure the value is set in tests
- Update documentation
Signed-off-by: Dan Ryan <dan.ryan@canonical.com>
=> Add global-timeout flag

.pre-commit-config.yaml, mypy.ini, src/bandersnatch/configuration.py, src/bandersnatch/master.py, src/bandersnatch/mirror.py, src/bandersnatch/package.py, src/bandersnatch/storage.py, src/bandersnatch/utils.py, src/bandersnatch_storage_plugins/filesystem.py, src/bandersnatch_storage_plugins/swift.py, src/runner.py
- Set Python 3.6
- Turn on a lot more mypy checks + warnings
- Exclude all plugins for now and focus on main code base
More work to get closer to finally close #15
=> Enforce mypy on all Core bandersnatch

setup.cfg
For some weird reason, python setup.py install thinks aiohttp-xmlrp is
the same module as aiohttp. So instead of install aiohttp-xmlrp first,
we'll install aiohttp first. Hopefully, this allows the docs to build.
Resolves #475.
=> Dirty fix so the docs can build (hopefully)

.travis.yml, src/bandersnatch/configuration.py, src/bandersnatch/mirror.py, src/bandersnatch/tests/test_configuration.py
- to configuration.validate_config_values
- Remove complexity from mirror function
- Move to file for code around what this actually does
- Unittest passing in no vaules so we always fallback to default
Spotted this when I sat down to work on #463
=> Move Configuration validation form mirror.mirror 

src/bandersnatch/delete.py, src/bandersnatch/main.py, src/bandersnatch/master.py, src/bandersnatch/mirror.py, src/bandersnatch/tests/test_delete.py, src/bandersnatch/tests/test_master.py, src/bandersnatch/tests/test_verify.py, src/bandersnatch/verify.py
- Move url_fetch to Master
- Pass in a Master object into verify
- Handle None for session timeout which fallsback to default of 5 hours
- Change delete to use Master() as well
Test: Make tests pass again + add one tests for fetch_url
Addresses parts of #463 
- We could still move more to mirror library potentially.
=> Refactor verify to use Master for HTTP calls

docs/conf.py
Related #556.
Since the bump to Sphinx 3.x, all of the Markdown documentation wasn't building
since the Markdown configuration was outdated. Instead of using source_parsers,
you just add the recommonmark extension. Also for good measure, Sphinx 3.0 < is
now required.
recommonmark version 0.4.0 and below are incompatible with Sphinx 3.x and since
we moved to Sphinx 3.x, a safeguard should be added.
---
Here's the built docs:
https://ichard26-testbandersnatchdocs.readthedocs.io/en/sphinx3/
=> Fix conf.py so Markdown docs can build properly

docs/conf.py, tox.ini
Turning warnings during the documentation build test will allow the test to catch
potentially dangerous documentation changes even when the doc build passes.
Resolves #556.
=> Turn warnings into errors while building docs to catch potentially dangerous documentation changes

.pre-commit-config.yaml, src/bandersnatch_filter_plugins/blacklist_name.py, src/bandersnatch_filter_plugins/filename_name.py, src/bandersnatch_filter_plugins/latest_name.py, src/bandersnatch_filter_plugins/metadata_filter.py, src/bandersnatch_filter_plugins/prerelease_name.py, src/bandersnatch_filter_plugins/regex_name.py, src/bandersnatch_filter_plugins/whitelist_name.py, src/bandersnatch_storage_plugins/filesystem.py, src/bandersnatch_storage_plugins/swift.py
Related: #15.
Type annotate the bandersnatch plugins.
@techalchemy, it would be nice if you could review this PR since you know these plugins the best. (Only if you have the time though)
=> Type annotate bandersnatch plugins

src/bandersnatch/main.py, src/bandersnatch/mirror.py, src/bandersnatch/tests/test_sync.py
Related issue: #560 
This PR added a `sync` sub command, which allows user to sync one or more packages .
```console
usage: bandersnatch sync [-h] package [package ...]
positional arguments:
package     The name of package to sync
optional arguments:
-h, --help  show this help message and exit
```
After a synchronization, bandersnatch refreshes global index files, while keeps status(serial) file intact. 
Would you please review the PR. If this implementation meets the requirement, I'll add some tests then.
=> Add "sync" command

.gitignore, src/bandersnatch/mirror.py, src/bandersnatch/package.py, src/bandersnatch/tests/test_mirror.py, src/bandersnatch/tests/test_package.py
Since the overall goal is to move operations which touch the filesystem away from the public API, this code should be moved to mirror.py.
I think this makes sense for a lot of other reasons, generally (annotated inline)
=> Move legacy directory cleanup to mirror.py

docs/bandersnatch.rst
The author of `src/bandersnatch/storage.py` seemed to have forgotten to add an entry for it in `docs/bandersnatch.rst` when the module was added. (nudge nudge @techalchemy :) This omission meant `sphinx-autodoc` didn't pick up the module when building the documentation.
See the updated docs here:
https://ichard26-testbandersnatchdocs.readthedocs.io/en/add_bandersnatch_storage_to_be_autodoced/
@cooperlees, I guess while this PR is open, should the plugins also be autodoc(ed) or should they stay undocumented for now?
=> Add an entry for storage module in docs/bandersnatch.rst

src/bandersnatch/filter.py, src/bandersnatch/mirror.py, src/bandersnatch/package.py, src/bandersnatch/tests/plugins/test_blacklist_name.py, src/bandersnatch/tests/plugins/test_filename.py, src/bandersnatch/tests/plugins/test_latest_release.py, src/bandersnatch/tests/plugins/test_prerelease_name.py, src/bandersnatch/tests/plugins/test_regex_name.py, src/bandersnatch/tests/plugins/test_whitelist_name.py, src/bandersnatch/tests/test_filter.py, src/bandersnatch/tests/test_mirror.py, src/bandersnatch/tests/test_package.py, src/bandersnatch/verify.py
Moved the filter loading into a class that loads all available plugins at once to avoid reading the config file everytime a plugin group wants to be loaded.
=> Refactored filter loading into seperate class

setup.cfg, src/bandersnatch/package.py, src/bandersnatch/tests/plugins/test_blacklist_name.py, src/bandersnatch/tests/plugins/test_filename.py, src/bandersnatch/tests/plugins/test_latest_release.py, src/bandersnatch/tests/plugins/test_prerelease_name.py, src/bandersnatch/tests/plugins/test_regex_name.py, src/bandersnatch/tests/test_filter.py, src/bandersnatch_filter_plugins/blacklist_name.py, src/bandersnatch_filter_plugins/filename_name.py, src/bandersnatch_filter_plugins/latest_name.py, src/bandersnatch_filter_plugins/prerelease_name.py, src/bandersnatch_filter_plugins/regex_name.py
Plugins apart of the release_plugin group no longer remove the releases that are passed into the filter.  Release removal is done now in a new function of the Package class ._filter_all_releases().  Also changed the plugin group of the exclude_platform filter to release_file_plugin.
Tests updated to account for new API.  Corrected a linux platform specifier in TestExcludePlatformFilter based on https://github.com/pypa/warehouse/pull/2010
=> Refactored the removal of releases for release_plugins to happen inside of Package

docs/filtering_configuration.md, setup.cfg, src/bandersnatch/tests/plugins/test_whitelist_name.py, src/bandersnatch_filter_plugins/whitelist_name.py
The user can add project specifiers to whitelist packages if they enable this new plugin, 'allowlist_release'.
=> Added new allowlist filter

README.md, docs/CODE_OF_CONDUCT.md, docs/CONTRIBUTING.md, docs/index.rst
For details, see:
* https://discuss.python.org/t/implementing-pep-609-pypa-governance/4745
=> The PyPA has adopted the PSF code of conduct

.readthedocs.yml, DEVELOPMENT.md, MAINTAINERS.md, README.md, docs/bandersnatch.rst, docs/bandersnatch_filter_plugins.rst, docs/bandersnatch_storage_plugins.rst, docs/conf.py, docs/filtering_configuration.md, docs/mirror_configuration.md, docs/modules.rst, requirements_docs.txt, src/bandersnatch/__init__.py, tox.ini
Updated version here ~(currently a bit broken, see to-do list below)~:
https://ichard26-testbandersnatchdocs.readthedocs.io/en/add_plugins_to_docs/index.html
To-do list:
=> Add plugins to documentation (and a few other documentation changes too)

src/bandersnatch/verify.py
Plugin filters appear to now require the full pkg dict rather than just the "info" section.
=> Fix passing package info to filters in verify action.

requirements_test.txt, src/bandersnatch/tests/test_filter.py, src/bandersnatch_filter_plugins/blacklist_name.py, src/bandersnatch_filter_plugins/whitelist_name.py
This PR aims to fix #284 by casefolding package names listed in the bandersnatch configuration as well as those obtained from the XML-RPC when checking for a match.
Also fixes copy-pasta remnants in the whitelist plugin comments/docstrings.
=> Casefold package names in blacklist/whitelist plugins

src/bandersnatch/package.py, src/bandersnatch/tests/test_package.py
In order to assist changing the mirror location or maintaining an
offline mirror at a different path symlinks to webdir/json/PKG should be
relative, addresses #636
=> Make webdir/pypi/json/PKG symlinks relative.

src/bandersnatch/tests/plugins/test_allowlist_name.py, src/bandersnatch/tests/plugins/test_blocklist_name.py, src/bandersnatch_filter_plugins/allowlist_name.py, src/bandersnatch_filter_plugins/blocklist_name.py
allowlist_release and blocklist_release were using the default construction of the Requirements object which creates a SpecifierSet in order to check requirements.  This SpecifierSet has a field 'prereleases' that gets set to false by default [0] and thus makes any comparisons against prerelease version specifiers return false even if the version would normally fall within the SpecifierSet.  Because of this behaviour allowlist_release and blocklist_release were filtering prereleases even if the prerelease filter wasn't set.
[0] https://packaging.pypa.io/en/latest/specifiers/#packaging.specifiers.SpecifierSet
=> Fixed allow/blocklist_release filtering prereleases

src/bandersnatch/__main__.py, src/bandersnatch/main.py
Fixes #383.
This should allow bandersnatch to be called with `python -m bandersnatch` for use with e.g. PyOxidizer.
=> add __main__ and program name override to ArgumentParser

src/bandersnatch/tests/plugins/test_allowlist_name.py, src/bandersnatch/tests/plugins/test_blocklist_name.py, src/bandersnatch_filter_plugins/allowlist_name.py, src/bandersnatch_filter_plugins/blocklist_name.py
Allowlist/blocklist project filters now create the Requirement object first before canonicalizing the package's name. This prevents canonicalize_name() from messing with the package's version specifier, if it was present, which could have caused a parse error inside the Requirement object if the package had the specifier "~=". Also, allowlist/blocklist release filters now how their package names canonicalized before checking to prevent casing mismatches.
=> Fixed name parsing issue for allow/blocklist project filters

src/bandersnatch/tests/plugins/test_latest_release.py, src/bandersnatch_filter_plugins/latest_name.py
Closes #659 
- Should we reintroduce the caching mechanism? Doing so only divides the time complexity by `self.keep`, which shouldn't be big anyway.
=> Fix latest_release plugin

docs/mirror_configuration.md, src/bandersnatch/configuration.py, src/bandersnatch/default.conf, src/bandersnatch/mirror.py, src/bandersnatch/tests/test_configuration.py, src/bandersnatch/tests/test_main.py, src/bandersnatch/tests/test_mirror.py
This changes adds a new configuration `release-files`, defaulting to
`true` (preserving existing behaviour), that allows a bandersnatch
mirror to skip syncing package release files. If set, this will also
check for `root_uri` being set, if not set will set it to
https://files.pythonhosted.org to ensure file links are still usable.
Resolves: #665
=> Add support for skipping mirroring release files

requirements.txt
This PR reverts 3a81bd28cb51d74f42a5a9ac20f106a623a6bd9d and 63926195169d79758f759c9e984a20e6a877bb5f in order to fix #707. Also closes #715.
=> Update aiohttp to 3.6.3; Downgrade multidict to 4.7.6, yarl to 1.5.1

Dockerfile, setup.cfg
By building the dependencies beforehand and reinstall on a slim version
weighting/bandersnatch   builder             503cec72f6a7        12 seconds ago      279MB
weighting/bandersnatch   base                0c7eb5b38afb        56 minutes ago      1.05GB
resulting image is +/- 4x smaller
=> now slimmer docker image

.dockerignore, Dockerfile, docs/filtering_configuration.md, setup.cfg, src/bandersnatch/tests/plugins/test_allowlist_name.py, src/bandersnatch_filter_plugins/allowlist_name.py, src/bandersnatch_filter_plugins/filename_name.py, tox.ini
because working with pip-compile generates requirements files with inline comments like
```
appdirs==1.4.4            # via black
black==20.8b1             # via -r requirements.in
certifi==2020.11.8        # via requests
```
and for now it's convenient to be able to paste it
=> packages allowlist can be defined from requirements like files

.github/dependabot.yml
One thing less to remember to update :D
Implemented according to https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/keeping-your-actions-up-to-date-with-dependabot
FYI a `dependencies` label [will be created automatically for use by Dependabot](https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates#labels). Unfortunately it appears there is no way to disable this behaviour. I guess configure PyUP to add that label too now?
=> Setup dependabot so Actions are automatically updated

.pre-commit-config.yaml, setup.cfg
- Remove useless and deprecated 'not_skip' option
-> see https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0/#not_skip
- Use isort 5+ profiles!
-> see https://pycqa.github.io/isort/docs/configuration/profiles/
- Remove unnecessary 'seed-isort-config' step in pre-commit config
-> https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0/#seed-isort-config
=> Clean up isort config after upgrade to 5+

docs/conf.py, docs/filtering_configuration.md, docs/index.rst, tox.ini
* Fix broken or redirecting links
* More intersphinx linking
Now references to packaging and filelock objects will be linked to their
external documentation.
Also removed urllib3 because no where does our code or docs reference it.
* Add linkcheck to tox config
This commit exists because I didn't want to have to remember to run
linkcheck routinely. Call me lazy if you will :P ... Well actually,
running linkcheck on CI via tox is a good way to make sure links
that go stale are noticed and fixed quickly.
I added --keep-going because it's better to get all of the warnings
in a single run then error out the build *than* only knowing that
there's at least one warning somewhere. Very useful if you are
looking at the CI logs as you can't just ask logs to tell what all the
warnings were about ;)
=> Fix links, improve docs CI, and improve external object linking

requirements.txt
Fixes https://github.com/pypa/bandersnatch/issues/802
idna 3 and above causes some extreme backtracking because
requests doesn't support the 3.x series. Requests is
heavily used by dependencies needed for bandersnatch
swift support so when requests must downgrade to a
version that vendors idna, dependency tree turns into a
variant that pip's new dependency resolver doesn't like
resolving. Although not installing the swift dependencies
or using the unpinned dependencies info in setup.cfg
works properly.
This also fixes the long pip install process which caused certain GHA
jobs to timeout.
=> Ban idna 3.x series due to compatibility issues

src/bandersnatch/tests/test_master.py, src/bandersnatch/tests/test_mirror.py, src/bandersnatch/tests/test_package.py, src/bandersnatch/tests/test_sync.py, src/bandersnatch/tests/test_verify.py
Will remove all of asynctest but will do in 2 stages.
1: All files but src/bandersnatch/tests/conftest.py
2: Remove to funky uses in src/bandersnatch/tests/conftest.py
- Remove coroutine magic mock
- Replace asynctest.patch with unittest.mock.patch() now it's smart enough to be async aware
Addresses most of #787
=> Remove asynctest 1

.github/workflows/ci.yml
Internal PRs (that come from branches of pypa/bandersnatch) match both
the push and pull_request events. This leads to a duplication of ci
checks on such PRs. Not only is it a waste of resources, it makes the
Status Checks UI more frustrating to go through.
Patch taken from:
https://github.community/t/duplicate-checks-on-push-and-pull-request-simultaneous-event/18012
--- 
see also: https://github.com/psf/black/pull/1986
=> Fix duplication of checks on internal PRs

src/bandersnatch_filter_plugins/filename_name.py
Will add platform tags specified in PEP 599 to `exclude_platform` filter:
- `manylinux2014_x86_64`
- `manylinux2014_i686`
- `manylinux2014_aarch64`
- `manylinux2014_armv7l`
- `manylinux2014_ppc64`
- `manylinux2014_ppc64le`
- `manylinux2014_s390x`
Addresses the PEP 599 portion of #830
=> Add linux platform types based on PEP 599

.github/workflows/changelog.yml, docs/CONTRIBUTING.md
Resolves #848.
I added a bonus feature that allows the check to be skipped if the pull request has a `skip news` label slapped on it. Look, I *had* to add something to overcomplicate it (might be useful for dependabot though). If you want me to get rid of it, please let me know!
=> Add changelog GHA workflow

.github/dependabot.yml
Had to do this after the workflow PR since dependabot needs the label to exist first :)
=> Use "skip news" label for Actions upgrades by dependabot

CHANGES.md, docs/mirror_configuration.md, src/bandersnatch/configuration.py, src/bandersnatch/default.conf, src/bandersnatch/mirror.py, src/bandersnatch/storage.py, src/bandersnatch/tests/ci-swift.conf, src/bandersnatch/tests/ci.conf, src/bandersnatch/tests/conftest.py, src/bandersnatch/tests/test_configuration.py, src/bandersnatch/tests/test_main.py, src/bandersnatch/tests/test_mirror.py, src/bandersnatch/unittest.conf, src/bandersnatch_storage_plugins/filesystem.py, src/bandersnatch_storage_plugins/swift.py
See issue #821. This pr implements:
1. check file size and modification time(upload time)
It currently does not allow user to force sha256sum check. And this pr is tested only on local filesystems, but not OpenStack.
=> Skip downloading based on file size and upload time instead of sha256sum

CHANGES.md, src/bandersnatch_storage_plugins/filesystem.py
Hi,
I saw RAM usage spike when bandersnatch starts up and found this line. It was effectively loading the entire file into memory as a string. Removing it seems to fix the memory issue.
Note: memory is used up even if log level is set above debug
=> Remove debugging line that loads entire files into memory.

CHANGES.md, src/bandersnatch/mirror.py, src/bandersnatch/tests/conftest.py
The way unittests were written caused us to mock the synchronize()
method to allow for testing we're setting up mirror object correctly.
Moving to asyncio has caused TypeErrors during the unittests so a very
dirty isinstace was added:
```python3
if not isinstance(mirror, Mock):  # type: ignore
changed_packages = await mirror.synchronize()
```
This commit eliminates the isinstance check seen above by mocking the
synchronize() method directly with unittest.mock.AsyncMock while patching
the whole mirror class.
The reason why the isinstance check was needed in the first place is
that unittest.mock.patch replaces methods with unittest.mock.MagicMock
instances by default. Even when unittest.mock.AsyncMock is needed.
Resolves GH-464.
=> Remove terrible isinstance check in mirror.py

src/bandersnatch/tests/test_verify.py, src/bandersnatch_filter_plugins/metadata_filter.py
This aims to reduce the warnings emitted during a full unit test run.
Unfornately a few warnings are within third-party packages that probably
won't be too easy to replace so they will be dealt with later.
The following warnings are now gone:
```
src/bandersnatch/tests/test_mirror.py::test_limit_workers
src/bandersnatch/tests/test_mirror.py::test_mirror_loads_serial
src/bandersnatch/tests/test_mirror.py::test_mirror_recovers_from_inconsistent_serial
src/bandersnatch/tests/test_mirror.py::test_mirror_generation_3_resets_status_files
src/bandersnatch/tests/test_mirror.py::test_mirror_generation_4_resets_status_files
/home/ichard26/programming/oss/bandersnatch/src/bandersnatch_filter_plugins/metadata_filter.py:203: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead …
```
=> Eliminate usages of deprecated APIs in unit tests

docs/CONTRIBUTING.md
This should reduce the friction when adding a changelog entry by quite a bit.
=> Point contributors to use Next PR Number

CHANGES.md, docs/conf.py, docs/filtering_configuration.md, docs/installation.md, docs/mirror_configuration.md, docs/serving.md, requirements_docs.txt, setup.cfg, tox.ini
- Migrate markdown documentation to use MyST-Parser since recommonmark
is going away.
- The "ReStructuredText syntax in Markdown" feature once provided by
recommonmark.AutoStructify has been replaced with MyST-Parser's syntax
extensions
- Fix the heading depths (i.e. remove a single `#` from most headers)
because MyST-Parser was emitting warnings
- Redo the Sphinx configuration to use the new parser
- Remove the `test` and `doc_build` extra installs because they are
developer-facing and duplicating them doesn't make sense.
- Remove `sphinx_rtd_theme` from the `doc_build` tox environment since
it's unnecessary
- Remove support for the following HTML themes in the Sphinx configuration:
cloud_sptheme,sphinx_bootstrap_theme, guzzle_sphinx_theme, sphinx_rtd_theme.
Only pypa_theme was ever …
=> Clean up stuff and migrate docs to MyST-Parser

src/bandersnatch/main.py, src/bandersnatch/tests/test_master.py
- Now we're >= 3.8 we can just use asyncio's run() method to get into an async context
Tests:
- Make sure all tests pass
- Wrap some Master tests to ensure we have a running event loop for them to grab
=> Move to using asyncio.run

CHANGES.md, src/bandersnatch/filter.py, src/bandersnatch/log.py, src/bandersnatch_filter_plugins/metadata_filter.py
- Bad if logic caused empty log line to be output
- Add file + line of log messages into bandersnatch logging format to help find bugs easier
Fixes #885
=> Fix logging bug in metadata_filter for SizeProjectMetadataFilter

CHANGES.md, src/bandersnatch/storage.py, src/bandersnatch_storage_plugins/filesystem.py, src/bandersnatch_storage_plugins/swift.py
This commit avoids copying the file over on (local) filesystem in most circumstances which reduces disk IOs.
When `source` and `dest` are on the same filesystem `shutil.move()` makes use of `os.rename()` which is desired to be atomic, otherwise it will copy and delete like in our previous implementation.
=> storage: add move_file() and use in rewrite() and update_safe()

.github/workflows/uvloop_ci.yml, CHANGES.md, setup.cfg, src/bandersnatch/main.py
- If uvloop is imported, lets try and use it
- Also added extra install to facilitate it for users
- i.e. `pip install bandersnatch[uvloop]` will now install it (one this is released to pypi)
=> Add support to use uvloop

.pre-commit-config.yaml, requirements_test.txt, src/bandersnatch/master.py, src/bandersnatch/mirror.py, src/bandersnatch/tests/test_main.py, src/bandersnatch/tests/test_mirror.py, src/bandersnatch/utils.py
Resolves #892 (i.e. supersedes)
I'm assuming this should get a skip news label
=> Update black from 20.8b1 to 21.4b0

CHANGES.md, src/bandersnatch/delete.py, src/bandersnatch/mirror.py, src/bandersnatch/storage.py, src/bandersnatch/tests/plugins/test_allowlist_name.py, src/bandersnatch/tests/test_delete.py
- Have asyncio call all potential blocking IO in said ThreadPoolExectuor in heavy main workload - e.g. downloading many packages @ once
- Grepped popular blocking calls to find
- This should help stop starving the loop from CPU time
- Modified all modules that call storage block calls to wrap them in the sotrage class executor with max thread == workers
Testing:
- Fix unittests to pass
- A lot just needed workers config
- Some just needed to have a loop / become coroutines
Fixes #584
=> Add a default ThreadPoolExecutor to storage plugin to wrap all IO

CHANGES.md, src/bandersnatch/configuration.py, src/bandersnatch/filter.py, src/bandersnatch/tests/test_configuration.py, src/bandersnatch_filter_plugins/allowlist_name.py, src/bandersnatch_filter_plugins/blocklist_name.py
- Remove the old allow/deny list naming
- Make it loud and proud in the CHANGES.md
Fixes #888
** This will require config updates from users using the legacy names!! **
=> Remove legacy support for non PC configuration names

src/bandersnatch/tests/ci-swift.conf, src/bandersnatch/tests/ci.conf, test_runner.py
- I killed peerme from pypi
- Also lets not download all the versions of black
- pinning >= 21.4b0
Faster now. Less to download.
=> Remove using peerme in Integration Tests + limit black versions

.gitignore, CHANGES.md, docs/conf.py, docs/index.rst, requirements_docs.txt, src/bandersnatch/main.py
Using sphinx-argparse-cli instead of sphinxcontrib-programoutput because
I got convinced by gaborjbernat via Discord.
Unfortanately this requires to move parser configuration to its own
function because that's what sphinx-argparse-cli uses as input. This
isn't that painful tho.
---
Preview: https://bandersnatch.readthedocs.io/en/add-cli-help/
Resolves #907.
=> Add autogenerated CLI help to docs index page.

CHANGES.md, src/bandersnatch/mirror.py, src/bandersnatch/tests/test_mirror.py
data-yanked is not generated in bandersnatch's simple page, this may confuse pip client because it will not install yanked release if not explictedly requested by user.
=> Generate data-yanked tag in simple page

src/bandersnatch/mirror.py
This PR fixes an exception when yanked-reason is present but empty, which is discovered when syncing the package borisml-0.0
Because it's a trivial fix to an exisiting commit, I don't think there should be a dedicated changelog entry...
=> data-yanked: fix exception when yanked-reason is present but empty

CHANGES.md, src/bandersnatch/mirror.py, src/bandersnatch/tests/plugins/test_storage_plugins.py
In the current implementation, when disk is full while wrapping up the sync, bandersnatch will truncate last-modified, generation and status files (and maybe more). This lead to a situation that the last successful sync's serial is lost, forcing next sync to start from verifying everything even the disk space issue is resolved.
Repacing some of the Path.write_text() and rewrite() to mitigate this problem. This closes #961
=>  Use update_safe when updating some repo-level metadata

.github/workflows/pypi_upload.yml, pyproject.toml
- `setup.py` direct invocations is deprecated
- https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html
- Lets be a good **PyPA** package and move to build PEP517 buld frontend that should do the right things
Test
- Show Python version used for test:
```
crl-m1:ptr cooper$ python3 -V
Python 3.9.10
```
- `/tmp/test_build/bin/pip install --upgrade pip setuptools`
- `/tmp/test_build/bin/pip install --upgrade build pip setuptools twine`
- `/tmp/test_build/bin/python -m build`
- Output: https://pastebin.com/rcmCp0cb
=> Move to PEP517 `build` package/frontend for packaging releases

.github/workflows/ci.yml, .github/workflows/ci_ubuntu.yml, .github/workflows/doc_build.yml, .github/workflows/docker_upload.yml
- As request by di tune our jobs
- To be fair our CI is pretty quick and we're not a busy project but I guess all helps
- Add only run on main branch push + pull requests to all on PR CI
- Also add the concurrency tweaks like `pip` to our main CI (`ci.yml` and `ci_ubuntu.yml`)
- We test the S3 plugin in ubuntu and it has some extra deps to mimic the S3 API etc.
- Fix broken docker_upload branch name of "master" to "main"
Let me know if there are any more tweaks we can do to be a team plater.
=> Limit CI running to help PyPA

src/bandersnatch_storage_plugins/filesystem.py, src/bandersnatch_storage_plugins/s3.py
- Some functions were not made Generators that should be
- Also file filesystem `open_file` to not need a dict + copy to s3 child object
- Remove `tf.has_changed = False` from filesystem + s3 update_safe fucntion as it's not used
Ignoring swift plugin due to #1081
Fixes #1074
=> s3: Fix typing + make functions same as Parent objects

.github/workflows/docker_upload.yml, CHANGES.md, Dockerfile
- Move all docker containers to Python 3.10
- Add `requirements_s3.txt` into container + install if it's the S3 build enabled via a docker build arg
- Update GitHub `docker_upload` action to also build + upload a s3 container
Test:
- `docker build -t bander_test --build-arg PY_VERSION=3.10 --build-arg WITH_S3=yes .`
- Will have to test docker_upload on the PR merge
Fixes #1055
=> Add S3 Docker Image support + uploading

docs/storage_options.md
Note that actually _using_ Swift as a backend seems to be currently busted -- I've been hacking on it to get it working, though.
=> Doc updates for Swift

.github/workflows/ci.yml, .github/workflows/ci_ubuntu.yml
pip now always does in-tree builds, see also https://github.com/pypa/pip/pull/11001
=> Remove deprecated --use-feature=in-tree-build in CI

docs/CONTRIBUTING.md, pytest.ini, tox.ini
- Contributing Docs updated
- Remove "lint" from tox.ini
- We were running py3 twice due to this - This should 1/2 "Run Unittests" step time for each OS
- Make tox run `pytest` with `--strict-markers`
- Set asyncio strict mode in pytest.ini as it's going to be default soon
- I don't know how to fix the asyncio warnings tho - e.g. getting running loop in `__init__`
=> CI Tweaks + Fixes + Doc Update

CHANGES.md, src/bandersnatch/mirror.py, src/bandersnatch/tests/test_mirror.py, src/bandersnatch/tests/test_sync.py
- Add 1.0 to our HTML to indicate we only support that
- Make a static class variable for version number so it will be easy to update in our two write locations
- Update test expectations to see it work how we want
Fixes #1121
=> Add PEP629 Version to Simple API HTML

.github/workflows/doc_build.yml, .github/workflows/pypi_upload.yml, .github/workflows/security.yml
actions/setup-python starting with version 4 doesn't have a default Python version. Also remove useless conditional in doc_build.
Fixes GH-1134.
=> Specify Python version in CI

CHANGES.md, src/bandersnatch/main.py, src/bandersnatch/mirror.py, src/bandersnatch/tests/test_mirror.py
Genrating simple root page is sometimes time-consuming , and it is not really used by pip( pip will use `https://pypi.org/simple/my-package/`  directly  ), thus not so important, this option could lead to an unsynced simple root page , but no critical damage is made.
=> make simple root page update optional

docs/index.rst, src/bandersnatch/storage.py
There are small typos in:
- docs/index.rst
- src/bandersnatch/storage.py
Fixes:
- Should read `normalized` rather than `normailzed`.
- Should read `initialize` rather than `intialize`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

CHANGES.md, setup.cfg, src/bandersnatch/__init__.py, src/bandersnatch/configuration.py, src/bandersnatch/default.conf, src/bandersnatch/mirror.py, src/bandersnatch/simple.py, src/bandersnatch/tests/conftest.py, src/bandersnatch/tests/plugins/test_allowlist_name.py, src/bandersnatch/tests/plugins/test_blocklist_name.py, src/bandersnatch/tests/plugins/test_filename.py, src/bandersnatch/tests/plugins/test_latest_release.py, src/bandersnatch/tests/plugins/test_metadata_plugins.py, src/bandersnatch/tests/plugins/test_prerelease_name.py, src/bandersnatch/tests/plugins/test_regex_name.py, src/bandersnatch/tests/plugins/test_storage_plugin_s3.py, src/bandersnatch/tests/plugins/test_storage_plugins.py, src/bandersnatch/tests/test_configuration.py, src/bandersnatch/tests/test_filter.py, src/bandersnatch/tests/test_main.py, src/bandersnatch/tests/test_mirror.py, src/bandersnatch/tests/test_simple.py, src/bandersnatch/tests/test_simple_fixtures.py, src/bandersnatch/tests/test_sync.py, src/bandersnatch/unittest.conf, test_runner.py
- Move to 6.0.0.dev0 version
- Add config for setting formats to save to storage
- `simple-format`
- Valid options: ALL, HTML or JSON
- Move `mirror` simple generation functions to new simple module
- Add new tests to test_simple.py
- Made tests be included with install by adding an __init__.py
Tests
- Add unittest coverage to SimpleAPI object
- Test valid and invalid format requests
- Test the JSON output for PEP691 compliance
- Per pacakge
- Global index
- Add check to Integration test to expect json index ...
=> Add PEP691 Format support

docs/mirror_configuration.md
Document `download-mirror` option in mirror_configuration, also mention it under `master` option to help people avoid misunderstand the usages.
=> docs: add download-mirror option

CHANGES.md, src/bandersnatch/tests/plugins/test_allowlist_name.py, src/bandersnatch_filter_plugins/allowlist_name.py
Fixed bandersnatch crash when requirements file contains [pip options.](https://pip.pypa.io/en/latest/reference/requirements-file-format/#supported-options)
Test result before the PR:
```
self = <[AttributeError("'Requirement' object has no attribute 'name'") raised in repr()] Requirement object at 0x7f230a96c5e0>
requirement_string = '--extra-index-url https://self-hosted-foo.netname/simple --trusted-host self-hosted-foo.netname'
def __init__(self, requirement_string: str) -> None:
try:
req = REQUIREMENT.parseString(requirement_string)
except ParseException as e:
>           raise InvalidRequirement(
f'Parse error at "{ requirement_string[e.loc : e.loc + 8]!r}": {e.msg}'
)
E           packaging.requirements.InvalidRequirement: Parse error at "'--extra-'": Expected W:(0-9A-Za-z) …
```
=> Issue #1033 - Fixed requirements file parsing when it contains pip options

CHANGES.md, src/runner.py, src/test_docker_runner.py
Added a runner optional argument, which does not break backwards compatibilty to limit the working hours of the mirroring process. This could be useful for peolpe who want to have full download bandwidth for their work / activities during the day and sync the repo during the night.
Hour range is expressed as `10-16`, `20-6` (with day-carry) or single hour `3`.
The optional parameter name is `--hours-range` and it defaults to `0-23` for backward compatibility.
=> Added possibility to limit hours range of mirroring activity

.pre-commit-config.yaml, CHANGES.md, MAINTAINERS.md, README.md, docs/CONTRIBUTING.md, docs/filtering_configuration.md, docs/installation.md, docs/mirror_configuration.md, docs/storage_options.md
https://github.com/pypa/bandersnatch/issues/1183 suggests adding "prettier" markdown formatter to pre-commit/ci, not sure if that means just any formatter to make markdown prettier or specifically the formatter called [prettier](https://prettier.io/) :stuck_out_tongue: 
This PR:
- Adds the [ExecutableBooks Markdown formatter](https://github.com/executablebooks/mdformat) to pre-commit. I chose this instead of prettier as for the reasons mentioned in the ['Why not use prettier instead?'](https://github.com/executablebooks/mdformat#why-not-use-prettier-instead) section of their readme
- Adds in a separate pre-commit workflow to execute pre-commit. Personally I prefer having these linting checks in a different workflow to the CI one, as this way the CI will still execute even if there are …
=> Add mdformat to pre-commit

CHANGES.md, requirements.txt, src/bandersnatch_filter_plugins/latest_name.py
- Allows moving to packaging 22.0
- Since this breaks no tests will drop the support
- Please feel free to come by and do a PR if this support is needed ... I'm not sure of options
Fixes #1311
=> Remove LegacyVersion support from latest_name plugin

CHANGES.md, docs/filtering_configuration.md, src/bandersnatch/tests/plugins/test_prerelease_name.py, src/bandersnatch_filter_plugins/prerelease_name.py
Make prerelease filter able to filter only specified packages.
May be useful for projects like `duckdb`, which publishes new prerelease for each commit.
=> packages config for prerelease filter

CHANGES.md, src/bandersnatch/master.py, src/bandersnatch/tests/test_master.py
- This call now 401s so there is no benefit of calling it
- Also spams logs with noise - So lets remove before more people open issues
Test:
- See tests pass
- Remove assertion of request being sent on StalePage as we no longer do ... That is this PRs purpose
Fixes #1334
=> Remove PURGE call on StalePage

.github/workflows/docker_upload.yml
Fixes #934.
Example run: https://github.com/ichard26/bandersnatch/actions/runs/3826906255
=> Don't run docker_upload workflow on forks

.github/workflows/ci.yml, .github/workflows/ci_ubuntu.yml, CHANGES.md, requirements_s3.txt, setup.cfg
- s3path 0.4.0 now supports 3.11
- This unlocks declaring py3.11 support for bandersnatch based on CI
Docker has not been upgraded to 3.11 yet ... Will do a seperate PR for that.
Test: Run tox locally with minio running
Resolves  #1314
=> Declare Python 3.11 Support

.github/workflows/docker_upload.yml, CHANGES.md, Dockerfile
We work in 3.11 so might as well start building docker in the faster available Python Runtime.
Please report any bugs!
Will look to go >= 3.10 later this year ... And move code to take advantage of that if we can.
=> Move Docker to 3.11

CHANGES.md, src/bandersnatch/mirror.py, src/bandersnatch/simple.py, src/bandersnatch/storage.py, src/bandersnatch/tests/plugins/test_storage_plugin_s3.py, src/bandersnatch/tests/plugins/test_storage_plugins.py, src/bandersnatch/tests/test_mirror.py, src/bandersnatch_storage_plugins/filesystem.py, src/bandersnatch_storage_plugins/s3.py, src/bandersnatch_storage_plugins/swift.py
Implemented a new `Storage.scandir(self, path)` API, used to replace `glob("**")`s for large directory listing.
=> Storage.scandir() method for replacing glob()s

CHANGES.md, src/runner.py
When running this as a mirror container, it might be desired to always update.
Signed-off-by: Tim Beermann <beermann@osism.tech>
=> Add parameter to allow passing "--force-check" to bandersnatch.

.pre-commit-config.yaml, src/bandersnatch_storage_plugins/swift.py
- swift needs extra params then Path
- Adding comment explaining and type ignore ...
Allows mypy upgrade ...
=> Update to mypy 1.0.1 + ignore subclass wrong typing

src/bandersnatch/tests/ci.conf, test_runner.py
- Update integration checks to use a newer than 23.1.0 package for deleting etc.
There was to many wheels to download for no value ...
=> Move CI to only download black>=23.1.0

CHANGES.md, src/bandersnatch/configuration.py, src/bandersnatch/simple.py, src/bandersnatch/tests/test_main.py, src/bandersnatch/tests/test_simple.py, src/bandersnatch/tests/test_simple_fixtures.py, src/bandersnatch/utils.py
PEP 691 specifies that each file's hashes dictionary must contain only
hash algorithms that can be passed, without arguments, to hashlib.new().
PyPI has started using a "blake2b_256" key for digests, which is blake2b
with the digest size set to 32 bytes, and makes it so that contents of
"digests" can't just be reused for the hashes dictionary.
This commit uses the value of configuration option digest_name to pick
a single supported key/value pair from the digests for use in the hashes
dictionary.
=> Use the configurable digest_name for simple JSON

CHANGES.md, setup.cfg, src/bandersnatch/__init__.py, src/bandersnatch/main.py, src/bandersnatch/mirror.py
- Fix + delete some uneeded comments
- Add more verbosity to release notes encouraging users to update all the Simple API files
=> Update version to 6.3.0 for release

CHANGES.md, src/bandersnatch/tests/plugins/test_filename.py, src/bandersnatch_filter_plugins/filename_name.py
- Seems the original author had no support for py2 and py3 release filename filtering
- Lets add in support
- Plus add unit test
Testing:
- Ran locally with setuptools only + filtered via `denylist` all py3 bdist releases
- `/tmp/tb/bin/bandersnatch -c /tmp/bandersnatch.conf --debug mirror`
- No longer see any **-py3-** only wheels via `find /tmp/pypi/web/ | grep '\.whl' | grep '\-py3\-'`
Fixes #1494
=> Add support for py[23] filename filtering

CHANGES.md, src/bandersnatch/default.conf, src/bandersnatch/simple.py, src/bandersnatch/tests/test_simple.py, src/bandersnatch/tests/test_simple_fixtures.py
- Move simple module to generate API 1.1 (JSON changes only)
- Since there is only additions we don't really break 1.0 so just moving to 1.1
- Seems pypi did this too
- PEP700: https://peps.python.org/pep-0700/
Tests:
- Fix tests for v1.1 new fields based on our mocked metadata
Fixes #1482
=> Add in PEP700 simple API v1.1 support

CHANGES.md, docs/filtering_configuration.md, src/bandersnatch/filter.py, src/bandersnatch/package.py, src/bandersnatch/tests/plugins/test_allowlist_name.py, src/bandersnatch_filter_plugins/allowlist_name.py
Make sure that pinned versions defined with `project_requirements_pinned` plugins are downloaded by disabling additional filter if version (range) is specified.
implements https://github.com/pypa/bandersnatch/issues/1599
=> Latest and version pinning clash

CHANGES.md, docs/filtering_configuration.md, src/bandersnatch/tests/plugins/test_latest_release.py, src/bandersnatch_filter_plugins/latest_name.py
Time based sorting can be used by setting `sort_by = time` together with `keep`
```
[latest_release]
keep = 3
sort_by = time
```
implements https://github.com/pypa/bandersnatch/issues/1433
=> #1433 improve release filtering by adding time based option

CHANGES.md, README.md, src/bandersnatch_docker_compose/README.md, src/bandersnatch_docker_compose/docker-compose.yml
This PR introduces the command configuration for the bandersnatch service in Docker Compose setup. It includes the default 'mirror' command and adds commented options for 'verify' and 'once' to provide alternatives for running bandersnatch.
The 'command' section is now clearly documented, making it easier for developers and sysadmins to understand and modify the behavior of the bandersnatch service.
Changes:
- Added 'command' directive to bandersnatch service with the default 'mirror' option.
- Included comments explaining how to use the 'verify' and 'once' commands.
- Explained the purpose of additional flags for the 'mirror' command.
- Provided documentation for the build context of the bandersnatch_nginx image.
=> Add command options and documentation to Docker Compose

requirements_s3.txt, setup.cfg, src/bandersnatch/tests/conftest.py, src/bandersnatch/tests/plugins/test_storage_plugin_s3.py, src/bandersnatch_storage_plugins/s3.py
- s/_s3_accessor/accessor/
- Move _S3DirEntry behind TYPE_CHECKING
- Remove backwards compatability
- Move scandir to use `S3Path.iterdir()`
- Again drop backward compatibility
Test:
- Keep tests with minio passing
=> Move to s3path 0.5.5

CHANGES.md, src/bandersnatch/config/diff_file_reference.py, src/bandersnatch/configuration.py, src/bandersnatch/tests/test_configuration.py
This replaces the implementation for custom `configparser` option references in the `diff-file` option, e.g. `diff-file = {{ section_option }}/myfilename.txt`.
Detection and handling for the custom syntax are moved into a submodule. The previous implementation did not preserve text before and after the reference part of the config value. This uses regular expressions to preserve any text before and after the reference.
Includes demonstration/regression tests added to the `bandersnatch/tests/configuration.py`.
=> Fix custom config reference syntax for the `diff-file` option

CHANGES.md, src/bandersnatch/mirror.py, src/bandersnatch/tests/test_main.py, src/bandersnatch/tests/test_mirror.py
This fixes path handling in the `mirror` subcommand that caused a diff file to be written to the current directory if `diff-file` wasn't set in the configuration file. This is the issue where `Path("")` becomes `Path(".")` and boolean-checks as truthy.
I encountered what might be an unexpected behavior when `diff-file` is set to an existing directory and `diff-append-epoch` is enabled. I've added a unit test to capture the current behavior, but it might be worth changing depending on how you feel about the compatibility break.
Split into 3 commits:
1. Removes a `diff_file` argument and attribute from `BandersnatchMirror`. The initializer accepted both `diff_file` and `diff_full_path`, and `diff_file` doesn't appear to be used anywhere. I went ahead and removed it while I was around then …
=> Fix diff-file being created when not configured

requirements_s3.txt, src/bandersnatch/tests/conftest.py, src/bandersnatch_storage_plugins/s3.py
- Move use uses of s3path configuration_map to import from accessor and use directly
Tests:
- See tests stay passing in GitHub actions
- I can not get them to pass locally ...
=> Move all use of s3path's configuration_map to public API

.github/workflows/ci.yml, .github/workflows/ci_ubuntu.yml, CHANGES.md, setup.cfg, src/bandersnatch/__init__.py, src/bandersnatch/tests/plugins/test_storage_plugin_s3.py, src/bandersnatch/tests/plugins/test_storage_plugins.py, src/bandersnatch_storage_plugins/s3.py
- Move to version 6.6.0dev0
- Make CI pass for 3.12
- Drop support for swift unless someone speaks up and wants to help support it - This will cause a temporary coverage reduction
- Move python_requires + GitHub actions to >= 3.11 only
- Leave swift for one more release + document deprecating support due to no one to help maintain
- Fix remaining s3path 3.12 fun
- Move to 3.12 private _generate_prefix until we workout correct way
- Move last missed uses of private configuration_map
Test:
- Run `/tmp/tb_312/bin/pre-commit run -a`
- Run tox in py312
- `/tmp/tb_312/bin/tox`
=> Add inital support for 3.12

.github/workflows/docker_upload.yml, CHANGES.md, Dockerfile
- Use 3.12 for filesystem + s3 docker images
- Due to lack of support / tests dropping building swift
- If someone is using, happy to bring back if support / maintanence is helped with
Test:
- Build on my laptop from root of bandersnatch repo
- `docker build --tag bandersnatch_312 .`
=> Update docker images to 3.12

CHANGES.md, src/runner.py
When no `--force-check` option is specified when using the `runner.py` the argument list for running bandersnatch command consists of `''` at the end which breaks the bandersnatch command execution: `bandersnatch: error: unrecognized arguments: `. This commit fixes this by only appending the "--force-check" argument if specified in runner.py call.
Closes #1754
=> Fix the command execution by runner.py

CHANGES.md, docs/CONTRIBUTING.md, pytest.ini, src/bandersnatch/tests/plugins/test_storage_plugin_s3.py
Show the user how to skip S3 tests.
=> test: allow skipping S3-related tests

.pre-commit-config.yaml, requirements_test.txt
This is to resolve an error seen when trying to setup `pre-commit` (see [1] for an example), the most relevant bit of the output:
An unexpected error has occurred: CalledProcessError: command: ('/pc/clone/LSIlsu0mQy2UjKm46aTi1Q/py_env-python3/bin/python', '-mpip', 'install', '.', 'types-filelock', 'types-freezegun', 'types-pkg_resources')
return code: 1
stdout:
Processing /pc/clone/LSIlsu0mQy2UjKm46aTi1Q
Preparing metadata (setup.py): started
Preparing metadata (setup.py): finished with status 'done'
Collecting types-filelock
Downloading types_filelock-3.2.7-py3-none-any.whl.metadata (1.4 kB)
Collecting types-freezegun
Downloading types_freezegun-1.1.10-py3-none-any.whl.metadata (1.4 kB)
stderr:
ERROR: Ignored the following yanked versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3
ERROR: Could not find …
=> Drop `types-pkg_resources`

pytest.ini, src/bandersnatch/tests/conftest.py, src/bandersnatch/tests/plugins/test_storage_plugins.py, tox.ini
I have been working on running the tests within a container to better match the CI environment and more easily test with multiple Python versions. I've kept my Docker/Docker Compose configuration in a sibling folder but needed to make a handful of changes to run the tests successfully.
1. The tests didn't have a way to configure the endpoint URL used for S3 plugin tests, so I added a check for an environment variable to allow overriding `localhost:9000` with something else.
2. There was a newline handling issue with a filesystem storage plugin test that only occurs when `sys.platform` doesn't match the platform the project source files were checked out of source control on. My host is Windows, so a sample file had `\r\n` endings, but when running the test in a Linux container the test …
=> Accommodations for running tests in containers that don't match the host OS

pytest.ini, requirements_test.txt, src/bandersnatch/tests/conftest.py, src/bandersnatch/tests/plugins/test_allowlist_name.py, src/bandersnatch/tests/plugins/test_blocklist_name.py, src/bandersnatch/tests/plugins/test_filename.py, src/bandersnatch/tests/plugins/test_latest_release.py, src/bandersnatch/tests/plugins/test_metadata_plugins.py, src/bandersnatch/tests/plugins/test_prerelease_name.py, src/bandersnatch/tests/plugins/test_regex_name.py, src/bandersnatch/tests/plugins/test_storage_plugins.py, src/bandersnatch/tests/test_delete.py, src/bandersnatch/tests/test_filter.py, src/bandersnatch/tests/test_main.py, src/bandersnatch/tests/test_master.py
This performs the same version changes as #1656 and #1797 in a single merge request, since the associated issues and fixes appear to be related:
- `pytest` => 8.3.4
- `pytest-asyncio` => 0.24.0
This is a major version increment for pytest and a [0ver](https://0ver.org/) minor version increment for pytest-asyncio.
Locally, I used `pytest-randomly` to shuffle the test execution order. Varying the test order uncovered a number of places where shared state was causing order-dependent failures.
1. Tests that indirectly invoke a call to `get_running_loop`/`get_event_loop` require an event loop to be available even if the test itself and the code under test is not asynchronous. Depending on execution order an event loop was not always active when needed. I added `asyncio` marks to test modules …
=> Upgrade test dependencies pytest and pytest-asyncio 

.github/workflows/ci.yml, .github/workflows/ci_ubuntu.yml, .github/workflows/docker_upload.yml, CHANGES.md, Dockerfile, setup.cfg, src/bandersnatch/__init__.py, src/bandersnatch_filter_plugins/filename_name.py
- Update classifiers
- Add 3.13 to CI
- Move Dockerfile to use 3.13 by default
- Add py3.13 to filter plugin `filename_name.py`
Test:
- Build docker locally
```
cooper@cooper-fedora-MJ0J8MTZ:~/repos/bandersnatch$ docker build -t bandersnatch_test --network host .
[+] Building 1.0s (23/23) FINISHED                                                                       docker:default
=> [internal] load build definition from Dockerfile                                                               0.1s
=> => transferring dockerfile: 1.23kB                                                                             0.0s
=> [internal] load metadata for docker.io/library/python:3.13-slim                                                0.4s
=> [internal] load metadata for …
```
=> Finish py3.13 support and move docker to 3.13

CHANGES.md, docs/mirror_configuration.md, src/bandersnatch/config/proxy.py, src/bandersnatch/master.py, src/bandersnatch/tests/test_master.py, src/bandersnatch/tests/test_proxy_config.py
This unifies proxy configuration handling for HTTP and SOCKS, so that:
- HTTP proxy URLs can be read from environment variables as well as the `mirror.proxy` option
- SOCKS proxy URLs can be read from the `mirror.proxy` option as well as environment variables
Fixes #1674
=> Add SOCKS support to proxy configuration parameter

.github/workflows/doc_build.yml, requirements_docs.txt
The CI was installing Python Docs Theme from GitHub:
https://github.com/pypa/bandersnatch/blob/f3e7640eac69ad536ad08d3f9c061ebbe599e285/requirements_docs.txt#L12
And the theme recently dropped Python 3.10 and 3.11: <https://github.com/python/python-docs-theme/pull/234>
But the CI is using 3.11:
<https://github.com/pypa/bandersnatch/blob/f3e7640eac69ad536ad08d3f9c061ebbe599e285/.github/workflows/doc_build.yml#L19>
The quickest fix is to pin `python-docs-theme==2025.2`, which is the most recent release and still supports Python 3.11.
---
There's another error when using Python 3.13 on the CI:
<details>
<summary>Details</summary>
```
WARNING: autodoc: failed to import module 'swift' from module 'bandersnatch_storage_plugins'; the following exception was raised:
looking for now-outdated …
```
=> Pin python-docs-theme to fix docs build

.github/dependabot.yml, CHANGES.md
Dependabot is now posting this comment as a warning:
> The reviewers field in the dependabot.yml file will be removed soon. Please use the code owners file to specify reviewers for Dependabot PRs. For more information, see this [blog post](https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/).
=> Update dependabot.yml to remove `reviewers` option
