- CHANGES.md
- src/bandersnatch/tests/test_utils.py
- src/bandersnatch/utils.py
- Add test
- Remove uneeded six usage from test_utils
> Convert os.uname to platform.uname

- setup.py
- src/bandersnatch/tests/test__bandersnatch_plugins__whitelist_name.py
- src/bandersnatch/tests/test_filter.py
- src/bandersnatch_filter_plugins/whitelist_name.py
This is a first shot at a plugin to address issue #33
> Add a project whitelist plugin and tests.

- .travis.yml
- test-requirements.txt
- Allow 3.8 to fail for now ...
> Move to stable 3.7 + 3.8 travis runs

- src/bandersnatch/verify.py
- Fixed #59
Thanks @electricworry
> Pass executor correctly to fix broken --json-update

- src/bandersnatch/verify.py
- Also handle dry run cleaner
- Fixes #61 
Thanks @electricworry
> Check if verify --delete is passed before deleting files

- CHANGES.md
- setup.py
- src/bandersnatch/__init__.py
- Bah - annoyed I missed this!
> Fix setup.py Homepage URL to Github

- src/bandersnatch/default.conf
- src/bandersnatch/main.py
- src/bandersnatch/mirror.py
- src/bandersnatch/package.py
- src/bandersnatch/tests/test_main.py
- src/bandersnatch/tests/test_package.py
- test-requirements.txt
- tox.ini
Configurable via `keep_index_versions`
Fixes #9
> Store N versions of index.html

- src/bandersnatch/verify.py
Set aiohttp to respect proxy vars like requests/urllib3
- Works but has a bug at the moment of printing that ~/.netrc is missing - https://pastebin.com/tSYtrvjr
- Tracked here: https://github.com/aio-libs/aiohttp/issues/3298
- Fixes #73
> Set aiohttp to respect proxy vars like requests/urllib3

- .travis.yml
- src/bandersnatch/filter.py
- src/bandersnatch/mirror.py
- src/bandersnatch/tests/ci.conf
- src/bandersnatch_filter_plugins/blacklist_name.py
- src/bandersnatch_filter_plugins/whitelist_name.py
- test_runner.sh
- Test a 2 package whitelisted bandersnatch run
- Assert the mirror run has correct output on the filesystem
- Also Run a verify - TODO: Inject bad files and ensure deleted (we don't test anything other than verify runs)
- Cleanup blacklist + whitelist logging to not be so spammy
All feedback welcome. Want to start basic and then add more edge cases.
Adresses #78
> Add Basic Integration Test

- README.md
> Add pyup shield to README.md

- CHANGES.md
- src/bandersnatch/__init__.py
> Update changes and move to 3.1.0 for release

- README.md
- src/bandersnatch/main.py
Hi 
I've added an option to move status file to /tmp directory and force bandersnatch to check the pypi master.
> add moving status file to /tmp and add it command-line option

- src/bandersnatch/tests/test_utils.py
- src/bandersnatch/tests/test_verify.py
- src/bandersnatch/utils.py
- src/bandersnatch/verify.py
- tox.ini
- I was lazy and never added tests ... So here are some - Will get to more. They're time consuming as I knew the would be.
- Moved utility functions to utils
- Make some utility tests a little better
- Add more type hinting while at it
> Test + Refactor verify

- .travis.yml
- azure-pipelines.yml
Can not hurt to test on more platforms. Next goal will be Windows on azure too.
> Make azure run tests on Mac OS X

- test-requirements.txt
- tox.ini
- Lets log our coverage over time ...
> Enable codecov in tox runs

- src/bandersnatch/package.py
> Generate data-requires-python attributes in index.html

- src/bandersnatch/tests/test_mirror.py
- src/bandersnatch/tests/test_package.py
- Also tidy up some flake8 finds on test_mirror.py + test_package.py
Tests #175 for #68
> Add a test for the new gen_data_requires_python function

- src/bandersnatch/package.py
- src/bandersnatch/tests/plugins/test_latest_release.py
- src/bandersnatch_filter_plugins/filename_name.py
- src/bandersnatch_filter_plugins/latest_name.py
> Latest releases plugin always keeps current version

- src/bandersnatch/package.py
- src/bandersnatch/tests/test_mirror.py
- src/bandersnatch/tests/test_package.py
Solve issue #141 (or I hope so).
last_serial is taken from JSON data as described [here](https://warehouse.pypa.io/api-reference/json/)
> add last_serial in Simple index.html

- src/bandersnatch/tests/test_verify.py
- src/bandersnatch/verify.py
- Had some time to kill on a plane
- Cover some queue methods and scheduling methods of verify
- Unfortunately mostly mocked out testing ...
> Add more verify tests

- requirements.txt
- Seems there are some deps we no longer need
- CI to confirm
> Do a fresh `pip freeze` to clean up requirements.txt

- docs/bandersnatch.rst
- docs/conf.py
- docs/index.rst
- Add a title to index so https://bandersnatch.readthedocs.org has one
- Remove some deprecations
- Include code of conduct
Fixes #226
> Add index title + Cleanup Docs

- MANIFEST.in
- docs/filtering_configuration.md
- src/bandersnatch/configuration.py
- src/bandersnatch/filter.py
- src/bandersnatch/tests/ci.conf
- src/bandersnatch/tests/plugins/test_whitelist_name.py
- src/bandersnatch/tests/test_configuration.py
- src/bandersnatch/unittest-deprecated.conf
- Continue to Support old blacklist plugins till 4.0.0
- Add loud deprecation and logging warnings
- Add tests
Fixes #215
> Add in support for [plugins] config section

- README.md
- docs/filtering_configuration.md
This PR fixes the following issues: [#218](https://github.com/pypa/bandersnatch/issues/218), [#219](https://github.com/pypa/bandersnatch/issues/219), [#220](https://github.com/pypa/bandersnatch/issues/220), [#221](https://github.com/pypa/bandersnatch/issues/221) and [#222](https://github.com/pypa/bandersnatch/issues/222).
> Fix README and doc

- .pyup.yml
> Add .pyup.yml to ignore setup.cfg

- src/bandersnatch/package.py
> Add Path.is_symlink to _save_simple_page_version

- .pyup.yml
- remove indent of requirement files like some other examples
Further attempts to fix https://github.com/pyupio/pyup/issues/350
> Fix pyup.yml by removing indentation

- .pyup.yml
- Reccomended by @Jwomers
Hope fully will allow me to add pyup.io back to the repo.
Addressing https://github.com/pyupio/pyup/issues/350
> [pyup.io] Add 2 spaces to all list items

- docs/index.rst
- docs/mirror_configuration.md
- src/bandersnatch/tests/test_configuration.py
- src/bandersnatch/tests/test_package.py
- Also add a little section into the documentation on how bandersnatch works at a very high level
- tox still passes locally ... Will see how CI does
Addresses some issues raised in #307
> Remove remaining delete references + tests

- docs/installation.md
- This has not been maintained
> Remove zc.buildout installation documentation

- .flake8
- .pre-commit-config.yaml
- docs/conf.py
- requirements_test.txt
- setup.cfg
- tox.ini
We should now pick up some more anti-patterns
Fixes #315
> Add flake8-bugbear + move to a non pre-commit flake8 run

- .github/workflows/pythonpackage.yml
- src/bandersnatch/tests/test_package.py
- Run lint, unittests + Integration
- MacOS + Linux
> Add GitHub Actions

- .github/workflows/docker_upload.yml
- Dockerfile
- src/runner.py
- Upload every push to master
- Will plan to add another Action on Release to tag an upload as a version in the future
> Add a Docker Publish GitHub Action

- Dockerfile
- README.md
- Also fix Dockerfile default CMD to match updated location
> Update README to offer Docker install option

- DEVELOPMENT.md
- README.md
Add documentation link to README
> Update the development docs

- src/bandersnatch_filter_plugins/filename_name.py
- src/bandersnatch_filter_plugins/metadata_filter.py
- src/bandersnatch_filter_plugins/prerelease_name.py
- src/bandersnatch_filter_plugins/regex_name.py
> Fix simple typo: specificed -> specified

- .pre-commit-config.yaml
- docs/conf.py
- setup.cfg
- src/bandersnatch/configuration.py
- src/bandersnatch/main.py
- src/bandersnatch/mirror.py
- src/bandersnatch/tests/test_mirror.py
- src/bandersnatch/tests/test_package.py
- src/bandersnatch/tests/test_utils.py
- tox.ini
- Incidental update to `tox.ini`
- Fixes #443
Signed-off-by: Dan Ryan <dan.ryan@canonical.com>
> Update pre-commit config

- .github/workflows/ci.yml
- src/bandersnatch/package.py
- src/bandersnatch/tests/test_mirror.py
- src/bandersnatch/tests/test_package.py
- src/bandersnatch/tests/test_utils.py
- test_runner.py
- We now pass, so lets ensure we don't regress
Helps #459
Fixes #23
> Add Windows GitHub CI

- docs/filtering_configuration.md
- Mention case / non normailized names are important
- Cleanup some markdown
> Update plugin docs

- setup.cfg
- src/bandersnatch/__init__.py
- src/bandersnatch/main.py
- Expect many bugs
- We need to exercise this code before 4.1.0 release
> Cleanup some stray swift fun + move to a dev version

- src/bandersnatch/master.py
- src/bandersnatch/package.py
It feels like it makes more sense as a utility function there, beside all the other API calls.
> Move http request code for package metadata to master.py

- setup.cfg
- src/bandersnatch/__init__.py
- src/bandersnatch/mirror.py
- src/bandersnatch/tests/test_mirror.py
- Due to a split bug we were always removing the TODO file
- Increment dev verison to dev2 for 4.1.0
Added a test so this hopefully does not occur again :D
Fixes #570
> Fix todo removal

- src/bandersnatch/master.py
- src/bandersnatch/package.py
- src/bandersnatch/tests/conftest.py
- src/bandersnatch/tests/plugins/test_blacklist_name.py
- src/bandersnatch/tests/plugins/test_filename.py
- src/bandersnatch/tests/plugins/test_latest_release.py
- src/bandersnatch/tests/plugins/test_prerelease_name.py
- src/bandersnatch/tests/plugins/test_regex_name.py
- src/bandersnatch/tests/plugins/test_storage_plugins.py
- src/bandersnatch/tests/test_package.py
Trying to break a couple of the self-contained changes out into smaller PRs.
> Minor refactor of Package class

- .github/workflows/ci.yml
- .github/workflows/pypi_upload.yml
> update actions/checkout to v2

- README.md
- docs/filtering_configuration.md
- setup.cfg
- src/bandersnatch/filter.py
- test_runner.py
in reference to https://github.com/pypa/bandersnatch/issues/731
> Renamed black/white to block/allow

- .pre-commit-config.yaml
- src/bandersnatch/mirror.py
- src/bandersnatch/tests/test_mirror.py
- Remove duplicate max() target serial finding code
- Add unittest on new function
@ichard26 - Fixed them :) Thanks for the motivation. Even got us some more test coverage and less duplicate code
> Update `pre-commit` via autoupdate + fix typing

- .github/workflows/docker_upload.yml
- So people can go as lean as possible etc.
> Build a swift and non swift docker image

- src/bandersnatch/tests/test_mirror.py
- src/bandersnatch/tests/test_verify.py
- src/bandersnatch/verify.py
> Handling of timeouts that can occur in verify.

- .readthedocs.yml
Lemme test this on my bandersnatch ReadTheDocs setup first. 
Also ReadTheDocs doesn't support 3.9 :(
> Make RTD aware of our love (need) for Python 3.8

- docs/installation.md
- mypy.ini
- src/bandersnatch/configuration.py
- src/bandersnatch/tests/test_configuration.py
- src/test_tools/test_xmlrpc.py
A PR fully created with the GitHub Web UI, aww yea!
> Update / cleanup stuff relating to Python 3.7 and below

- .flake8
- CHANGES.md
- src/bandersnatch/storage.py
> Check if we need to actually attempt to load plugins

- CHANGES.md
- docs/filtering_configuration.md
- requirements.txt
- requirements_test.txt
- setup.cfg
- src/bandersnatch/mirror.py
- src/bandersnatch/tests/plugins/test_metadata_plugins.py
- src/bandersnatch_filter_plugins/allowlist_name.py
- src/bandersnatch_filter_plugins/blocklist_name.py
- src/bandersnatch_filter_plugins/metadata_filter.py
WIP. Functionally works, but need to document, add tests, and make some improvements. Also fixed some issues spotted on the way.
> Implement a new filter that denied/allows projects based on total filesize.

- .pre-commit-config.yaml
- src/bandersnatch/tests/test_package.py
- src/bandersnatch_storage_plugins/swift.py
Also remove various now unnecessary type: ignore comments.
see also https://github.com/pypa/bandersnatch/pull/832#issuecomment-782707290
> Bump mypy from 0.790 to 0.812

- .github/workflows/changelog.yml
- When news / changelog CI fails have a blatant echo to say "Add the line" to try help people not get confused
cc: @ichard26
> Add helpful echo to direct people to add changes 

- CHANGES.md
- requirements_test.txt
- setup.cfg
- src/bandersnatch/tests/conftest.py
Here's the PR I promised! 
This was easier than I had expected.
Resolves GH-787
> Replace asynctest with unittest.mock

- CHANGES.md
- src/bandersnatch/mirror.py
Closes pypa/bandersnatch#864
Co-authored-by: @shankerwangmiao
> Run get_hash() in executor (#877)

- README.md
Removed IRC client and added discord chat in contact section.
Fixes #924
> Added discord chat to contact

- README.md
the link of coverage badge is incorrect, should be bandersnatch
> fix coverage badge link

- CHANGES.md
- docs/index.rst
- docs/storage_options.md
- Add brief docs explaining bandersnatch backend storage options
- Need to fill in the serving options for S3 + Swift
> Add Storage Documentation

- .github/workflows/ci_ubuntu.yml
- docs/CONTRIBUTING.md
- requirements_s3.txt
- setup.cfg
- src/bandersnatch/__init__.py
- Move version to 5.1.0.dev0
- Remove version pinning from setup.cfg + add all deps + pin in requirements_s3.txt
- Add documentation on how to run S3 integration/unittests locally
- Change CI to use offical minio docker image
> Clean Up Deps + Update Unittest running Documentation

- CHANGES.md
- tox.ini
- Stop using extra that install latest of everything
- Used pins so we know what version of deps tests are using
> Change tox to use pinned deps

- docs/storage_options.md
related to: https://github.com/pypa/bandersnatch/issues/552
> add s3 serving documents

- .pyup.yml
- CHANGES.md
- requirements_s3.txt
- s3 deps release a lot so lets reduce churn here to be more manageable
> Change pyup to run monthly

- docs/filtering_configuration.md
- someone must have made the anchor names more meaningful ...
> Update the URL to PEP440 Version Specifiers anchor

- .github/workflows/ci.yml
- .github/workflows/ci_ubuntu.yml
- CHANGES.md
- requirements_docs.txt
- setup.cfg
- src/bandersnatch/__init__.py
- Also add CI to run in python 3.10 + claim support
> Update version to 5.1.0 for release

- .github/workflows/ci.yml
- .github/workflows/ci_ubuntu.yml
- CHANGES.md
- requirements_s3.txt
- setup.cfg
> Support Python 3.10 on S3

- src/bandersnatch/configuration.py
- src/bandersnatch/master.py
- src/bandersnatch/mirror.py
- src/bandersnatch/package.py
- src/bandersnatch/storage.py
- src/bandersnatch_filter_plugins/metadata_filter.py
- src/bandersnatch_filter_plugins/regex_name.py
- Remove all from:
- master.py
- mirror.py (expcet on any any lambda fun)
- package.py
- storage.py
- bandersnatch_filter_plugins/regex_name.py
Fixes #1075
> Remove as much `type: ignore` as possible

- docs/CONTRIBUTING.md
- docs/filtering_configuration.md
- docs/storage_options.md
- Fix pep.python.org redirects
- Fix contrbuting GitHub links
> Fix all doc links

- docs/index.rst
Noticed that the list wasn’t rendering correctly.
> docs: correctly render a list

- CHANGES.md
- docs/CONTRIBUTING.md
- docs/index.rst
- docs/mirror_configuration.md
- setup.cfg
- src/bandersnatch/__init__.py
- Add config options to docs explaining valid setting + docs fixes
> Update version + CHANGES.md for 6.0.0 release

- src/bandersnatch/simple.py
Noticed this in https://github.com/python/mypy/pull/13686#issuecomment-1251019429
> Fix missing method call

- CHANGES.md
- docs/filtering_configuration.md
- src/bandersnatch/tests/plugins/test_allowlist_name.py
- src/bandersnatch_filter_plugins/allowlist_name.py
Sorry for the double PR, but I did the previous one erroneously on the main branch, which I wanted to clean for a new PR.
> Issue #1032 - Added glob on requirements allowlist

- .pre-commit-config.yaml
- CHANGES.md
- src/bandersnatch/mirror.py
- src/bandersnatch/tests/plugins/test_allowlist_name.py
- src/bandersnatch/tests/plugins/test_filename.py
- src/bandersnatch/tests/plugins/test_latest_release.py
- src/bandersnatch/tests/plugins/test_prerelease_name.py
- src/bandersnatch/tests/plugins/test_regex_name.py
- src/bandersnatch/tests/plugins/test_storage_plugins.py
- src/bandersnatch/tests/test_mirror.py
- src/bandersnatch/tests/test_simple_fixtures.py
- src/bandersnatch/verify.py
- src/bandersnatch_filter_plugins/metadata_filter.py
- src/bandersnatch_storage_plugins/s3.py
- src/test_docker_runner.py
- Get all the formatting wins - All look sane to me
- Love some of the fstring fixes ...
Tested: `pre-commit run-files -a`
> Move to black `--preview`

- .flake8
- CHANGES.md
- src/bandersnatch/tests/plugins/test_allowlist_name.py
- src/bandersnatch_filter_plugins/allowlist_name.py
- src/bandersnatch_filter_plugins/encoding.py
> Fixed import of packages from requirement files with UTF-16 encoding

- .pre-commit-config.yaml
- CHANGES.md
- mypy.ini
- src/bandersnatch/master.py
- src/bandersnatch/package.py
- src/bandersnatch/simple.py
- src/bandersnatch/tests/plugins/test_storage_plugins.py
- src/bandersnatch/tests/test_mirror.py
- src/bandersnatch_storage_plugins/filesystem.py
- src/bandersnatch_storage_plugins/s3.py
- src/bandersnatch_storage_plugins/swift.py
- Run pre-commit
- `pre-commit run -a`
- Apply all suggested formatting + upgrade recommendations
Test:
- See unit tests stay passing via local tox run + CI
> Move black, mypy + ise pyupgrade to be baselined on >= python 3.11

- requirements_test.txt
> Move to pytest-asyncio==0.23.7

- CHANGES.md
- requirements.txt
- setup.cfg
- src/bandersnatch/filter.py
- Use this library to find our entry point groups
Test: See unit tests stay passing and warning go away
> Move from pkg_resource to importlib_metadata

- .gitignore
- CHANGES.md
- MAINTAINERS.md
- README.md
- docs/CONTRIBUTING.md
- docs/installation.md
> docs: various tweaks

- CHANGES.md
- docs/mirror_configuration.md
- src/bandersnatch/defaults.conf
- src/bandersnatch/master.py
- src/bandersnatch/mirror.py
- src/bandersnatch/tests/test_configuration.py
> feat: allow using a non-https mirror via config

- requirements.txt
Remove >= and let's hard ping again if we can
> Update to async-timeout 5.0.1

- src/bandersnatch/tests/test_mirror.py
- src/bandersnatch/tests/test_simple.py
For #1877. 😄 
Small diff; feel free to copy-paste or cherry-pick or whatever if that's easier than chained PRs. 😬
> Mark more secretly asynchronous tests to pytest-asyncio

- README.md
Python 3.11 is the minimum version
> Bump doc for Python 3.11
